version: '3'
services:
  web:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: conteneurapache
    depends_on:
      - db

    volumes:
      - ./app:/var/www/html #volume pour le conteneur apache
    ports:
      - "8000:80"
    networks:
      - reseaussi

  db:
    container_name: db
    build:
      context: ./mysql
      dockerfile: Dockerfile
    restart: always
    env_file: env
    ports:
      - "9906:3306"
    volumes:
      - ./db_data:/var/lib/mysql  # Ajout du volume pour la base de données
    networks:
      - reseaussi

networks:
  reseaussi:

